# Generated by Django 4.1.3 on 2023-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_home_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_no',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
